export const codexReviewDate = 'September 25, 2026';
export const codexPicks = [
  {
    ticker: 'LRCX',
    headline: 'The clearest test of memory-cycle fears',
    summary: 'My first choice: a large pullback and a report that can show memory investment is lasting longer than feared.',
    why: 'A strong December outlook could push earnings estimates higher and reduce the discount investors attach to the next memory downturn. I prefer Lam because the next guide gives a direct test of this thesis.',
    baseline: 'Management already guides September revenue to $8.10bn ± $400m and adjusted EPS to $2.15 ± $0.15. Strong reported growth alone would not be a surprise.',
    catalyst: 'December revenue and operating-margin guidance that causes analysts to raise forward estimates, supported by durable memory and foundry spending.',
    invalidator: 'A strong September quarter followed by a soft outlook, customer spending delays, or margins weakening as sales rise.',
    sa: 'SemiAnalysis’s August 21 equipment work is constructive on Lam. That supports the business thesis; this number-one ranking and the earnings trigger are my judgment.',
    sourceUrl: 'https://investor.lamresearch.com/2026-07-29-Lam-Research-Corporation-Reports-Financial-Results-for-the-Quarter-Ended-June-28,-2026',
    sourceLabel: 'Lam · July 29 results and guidance',
  },
  {
    ticker: 'MKSI',
    headline: 'The deepest reset, with orders still to convert',
    summary: 'My second choice: the biggest decline in this five, with earnings upside if subsystem and packaging demand converts into cash.',
    why: 'The combination of a large price reset and exposure to equipment subsystems and advanced packaging offers a compelling recovery setup. Better order conversion, margins and cash flow could change both profit estimates and perceptions of balance-sheet risk.',
    baseline: 'Q3 guidance is $1.35bn ± $40m of revenue and $3.58 ± $0.31 of adjusted EPS. The case needs progress beyond this existing baseline.',
    catalyst: 'A stronger following-quarter outlook, supported by actual subsystem shipments, favorable mix and cash generation.',
    invalidator: 'Order strength fails to become revenue, working capital absorbs the profit improvement, or debt remains a constraint.',
    sa: 'SemiAnalysis’s July 27 capacity work names MKSI among subsystem beneficiaries. I am extending that theme into an earnings trade; MKSI is not a direct substrate manufacturer.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1049502/000119312526335274/mksi-ex99_1.htm',
    sourceLabel: 'MKS · Q2 results and Q3 guidance',
  },
  {
    ticker: 'MTSI',
    headline: 'Connectivity upside, measured before tax benefits',
    summary: 'My third choice: a substantial pullback with a connectivity catalyst that broadens the list beyond equipment and substrates.',
    why: 'Continued datacenter demand could translate into higher sales and operating profit through the changing interconnect architecture. I rank it ahead of Ibiden because the remaining price reset is larger, while requiring proof that operating performance drives the upside.',
    baseline: 'Q4 guidance is $415–425m of revenue, 60–61% adjusted gross margin and $1.97–2.03 adjusted EPS. The guided adjusted tax rate is only 3%.',
    catalyst: 'Next-quarter sales and operating-margin guidance that supports higher earnings even after using a more normal tax rate.',
    invalidator: 'An EPS beat largely explained by tax, customer demand slowing, or product transitions impairing margins.',
    sa: 'SemiAnalysis’s June 9 work favors MTSI relative to expectations. Its August NPO work also means the case cannot assume every optical transition is delayed.',
    sourceUrl: 'https://ir.macom.com/news-releases/news-release-details/macom-reports-fiscal-third-quarter-2026-financial-results',
    sourceLabel: 'MACOM · August 6 results and guidance',
  },
  {
    ticker: '4062',
    headline: 'The most direct substrate pricing expression',
    summary: 'My fourth choice: confirmed pricing and utilization benefits make the substrate thesis tangible, despite a smaller pullback.',
    why: 'Ibiden offers a direct way to express high-end substrate scarcity. Further improvement in price, mix and factory utilization could show that the profit upgrade is still developing, rather than already exhausted.',
    baseline: 'The company has already raised full-year operating-profit guidance from ¥90bn to ¥127bn, a 41.1% increase. Its release cites stronger demand, higher prices and utilization.',
    catalyst: 'Quarterly operating performance and the remaining-year outlook that support further upgrades beyond the August forecast.',
    invalidator: 'Repricing is already fully reflected in guidance, costs or yields offset the gains, or a split-basis error makes the valuation look cheaper than it is.',
    sa: 'SemiAnalysis explicitly preferred Ibiden within substrates on June 25. This is a dated relative preference, not a fresh price target after the subsequent company upgrade.',
    sourceUrl: 'https://www.ibiden.com/ir/items/gyousekishuusei2026Q1.pdf',
    sourceLabel: 'Ibiden · August 4 forecast revision',
  },
  {
    ticker: 'FORM',
    headline: 'More testing per advanced chip',
    summary: 'My fifth choice: rising test requirements can support earnings, although the smaller reset leaves less room for disappointment.',
    why: 'More demanding memory and packaging designs can increase probe-card and test demand. A report showing repeatable margins alongside a stronger forward outlook could persuade investors to treat growth as more durable.',
    baseline: 'Q2 revenue was $258.2m with $0.82 non-GAAP EPS. Q3 guidance is $270m ± $10m and $0.86 ± $0.09 non-GAAP EPS.',
    catalyst: 'Stronger next-quarter demand and margins across high-value test applications, sufficient to lift forward profit estimates.',
    invalidator: 'Favorable product mix proves temporary, customer demand is concentrated or lumpy, or the next guide merely meets an already strong expectation.',
    sa: 'SemiAnalysis’s June 9 work is constructive on FORM and test exposure. I favor this direct test thesis, with NVMI the first equipment challenger to reassess.',
    sourceUrl: 'https://investors.formfactor.com/news-releases/news-release-details/formfactor-inc-reports-2026-second-quarter-results',
    sourceLabel: 'FormFactor · Q2 results and Q3 guidance',
  },
] as const;
